import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='w-100 h-100'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container h-100 w-100">
        <div className='box-container d-flex justify-content-center align-items-center h-100 w-100'>
          <div className='p-4 box border d-flex flex-column justify-content-evenly' style={{width:'300px',height:'200px'}}>
            <input type="text" name="color" id="input-color" className='form-control d-flex' style={{margin:'0px auto'}}></input>
            <button type="button" className="btn btn-primary ml-auto" style={{margin:'0px auto',width:'100%'}}>Send TX</button>
          </div>
        </div>
      </div>
    </div>
  )
}
